version: "3.4"

services:
  client:
    build:
      context: .
      args:
        SHARED_SERVICES_ACCOUNT_ID: "${SHARED_SERVICES_ACCOUNT_ID}"
        LOCAL_DEVELOPMENT: "true"
    volumes:
      - './test:/test'
      - './spec:/spec'
    expose:
      - "1812/udp"
      - "1813/udp"
      - "2083/tcp"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: root
      DB_NAME: network_access_control_development_admin
      CONTAINER_NAME: "test-client"
    user: root
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
      adminnet:

  radsecproxy:
    build:
      context: ./test/radsecproxy
      args:
        SHARED_SERVICES_ACCOUNT_ID: "${SHARED_SERVICES_ACCOUNT_ID}"
        LOCAL_DEVELOPMENT: "true"
    volumes:
      - './test/certs:/certs'
    expose:
      - "1812/udp"
      - "1813/udp"
      - "2083/tcp"
      - "18120/udp"
    environment:
      CONTAINER_NAME: "radsecproxy"
      EAP_PRIVATE_KEY_PASSWORD: "whatever"
      RADSEC_PRIVATE_KEY_PASSWORD: "whatever"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8

  server:
    build:
      context: ./network-access-control-server/
      args:
        SHARED_SERVICES_ACCOUNT_ID: "${SHARED_SERVICES_ACCOUNT_ID}"
        LOCAL_DEVELOPMENT: "true"
    expose:
      - "1812/udp"
      - "1813/udp"
      - "2083/tcp"
    extra_hosts:
      - "example.com:10.5.0.9"
      - "www.example.com:10.5.0.9"
    volumes:
      - './test:/test'
      - './authorised_macs:/etc/freeradius/3.0/authorised_macs'
    user: root
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: root
      DB_NAME: network_access_control_development_admin
      ENABLE_OCSP: "yes"
      OCSP_OVERRIDE_CERT_URL: "yes"
      OCSP_URL: "http://www.example.com:80"
      LOCAL_DEVELOPMENT: "true"
      CONTAINER_NAME: "server"
      ENABLE_CRL: "no"
      EAP_PRIVATE_KEY_PASSWORD: "whatever"
      RADSEC_PRIVATE_KEY_PASSWORD: "whatever"
      VERBOSE_LOGGING: "true"
    command: sh -c "/scripts/bootstrap.sh"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
      adminnet:

  certgenerator:
    user: root
    build:
      context: ./test/generate_certs
      args:
        SHARED_SERVICES_ACCOUNT_ID: "${SHARED_SERVICES_ACCOUNT_ID}"
    command: sh -c "/bootstrap.sh"

  ocsp:
    build:
      context: ./ocsp
      args:
        SHARED_SERVICES_ACCOUNT_ID: "${SHARED_SERVICES_ACCOUNT_ID}"
    volumes:
      - ./ocsp/default.conf:/etc/nginx/conf.d/default.conf:ro
      - './test:/test'
    expose:
      - "80/udp"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.9
      adminnet:

  schema-test-client:
    build:
      context: ./policy_engine_schema_test_client
      args:
        SHARED_SERVICES_ACCOUNT_ID: "${SHARED_SERVICES_ACCOUNT_ID}"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: root
      DB_NAME: network_access_control_development_admin
    volumes:
      - './policy_engine_schema_test_client/test:/test'
      - './policy_engine_schema_test_client/stubs/radiusd:/usr/local/lib/python3.8/site-packages/radiusd'
    expose:
      - "80/udp"
    networks:
      adminnet:

networks:
  vpcbr:
    name: vpcbr
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
  adminnet:
    external: true
    name: adminnet
